apiVersion: v1
kind: Service
metadata:
  name: app
  #namespace: app
spec:
  ports:
    - name: app
      port: 5000
      targetPort: 5000
      nodePort: 30000
  selector:
    app: app
  type: NodePort

