apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-authentication
spec:
  storageClassName: standard
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /tmp/data