apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: authentication-pv
  name: authentication-pv
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
status: {}