apiVersion: v1
kind: Service
metadata:
  name: authentication
  #namespace: authentication
spec:
  ports:
    - name: authentication
      port: 5002
      targetPort: 5002
      nodePort: 30002
  selector:
    app: authentication
  type: NodePort