apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-redis
spec:
  storageClassName: standard
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /tmp/redis/data