apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
data:
  redis.conf: |-
    bind 0.0.0.0
    protected-mode no
    port 6379
    timeout 0
    tcp-keepalive 0
    dbfilename dump.rdb
    dir ./
    save ""
    appendonly no
    cluster-enabled no
    maxmemory-policy noeviction
    maxmemory-samples 5
    maxclients 10000
    daemonize no
    requirepass ""
